name: gen
channels:
  - defaults
dependencies:
  - blas=1.0=mkl
  - ca-certificates=2020.1.1=0
  - certifi=2019.11.28=py37_0
  - cycler=0.10.0=py37_0
  - freetype=2.9.1=hb4e5f40_0
  - intel-openmp=2019.4=233
  - kiwisolver=1.1.0=py37h0a44026_0
  - libcxx=4.0.1=hcfea43d_1
  - libcxxabi=4.0.1=hcfea43d_1
  - libedit=3.1.20181209=hb402a30_0
  - libffi=3.2.1=h475c297_4
  - libgfortran=3.0.1=h93005f0_2
  - libpng=1.6.37=ha441bb4_0
  - matplotlib=3.1.3=py37_0
  - matplotlib-base=3.1.3=py37h9aa3819_0
  - mkl=2019.4=233
  - mkl-service=2.3.0=py37hfbe908c_0
  - mkl_fft=1.0.15=py37h5e564d8_0
  - mkl_random=1.1.0=py37ha771720_0
  - ncurses=6.2=h0a44026_0
  - numpy-base=1.18.1=py37h6575580_1
  - openssl=1.1.1d=h1de35cc_4
  - pip=20.0.2=py37_1
  - pyparsing=2.4.6=py_0
  - python=3.7.6=h359304d_2
  - python-dateutil=2.8.1=py_0
  - readline=7.0=h1de35cc_5
  - setuptools=45.2.0=py37_0
  - six=1.14.0=py37_0
  - sqlite=3.31.1=ha441bb4_0
  - tk=8.6.8=ha441bb4_0
  - tornado=6.0.3=py37h1de35cc_3
  - wheel=0.34.2=py37_0
  - xz=5.2.4=h1de35cc_4
  - zlib=1.2.11=h1de35cc_3
  - pip:
    - numpy==1.18.1
    - opt-einsum==3.1.0
    - pyro-api==0.1.1
    - pyro-ppl==1.2.1
    - torch==1.4.0
    - tqdm==4.43.0
prefix: /anaconda3/envs/gen

